name: spell_num
description: Convert numbers to Enlgish words - up to 999 million with/without decimal places.
version: 0.1.1
homepage: https://github.com/LoayKhodor/spell_num


environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: