name: spell_num
description: Convert numbers to English words with decimal places and currencies.
version: 0.2.0
homepage: https://github.com/LoayKhodor/spell_num


environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: